### ISSUE TITLE
Fails when trying to get fees from kraken exchange

### ISSUE THREAD

**Issue by uwefassnacht** [5an1ty/BitBot#15]
Looks like an issue when getting the trading fees:

~/code/BitBot $ node app.js
[18-02-2016 13:56:37] - INFO: ----------------------------------------------------
[18-02-2016 13:56:37] - INFO: Starting BitBot v0.9.7
[18-02-2016 13:56:37] - INFO: Real Trading Enabled = false
[18-02-2016 13:56:37] - INFO: Working Dir = /Users/myuser/code/BitBot
[18-02-2016 13:56:37] - INFO: ----------------------------------------------------
[18-02-2016 13:56:37] - INFO: ----------------------------------------------------
[18-02-2016 13:56:37] - INFO: Launching trader module.
[18-02-2016 13:56:37] - INFO: Trade at start = false
[18-02-2016 13:56:37] - INFO: ----------------------------------------------------
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[18-02-2016 13:56:37] - INFO: Downloader started!
/Users/myuser/code/BitBot/exchanges/kraken.js:196
        }).fee);
          ^

TypeError: Cannot read property 'fee' of undefined
    at handler (/Users/myuser/code/BitBot/exchanges/kraken.js:196:11)
    at null.<anonymous> (/Users/myuser/code/BitBot/exchanges/kraken.js:85:5)
    at Request._callback (/Users/myuser/code/BitBot/node_modules/kraken-exchange-api/kraken.js:151:15)
    at Request.self.callback (/Users/myuser/code/BitBot/node_modules/kraken-exchange-api/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/myuser/code/BitBot/node_modules/kraken-exchange-api/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/myuser/code/BitBot/node_modules/kraken-exchange-api/node_modules/request/request.js:963:12)

**Comment by 5an1ty** [comment]
Hi @uwefassnacht,

Thanks for having a look at BitBot! That error seems strange as I'm currently running this API wrapper in production.

The version currently on Github is a bit dated and I'm doing big changes in a rewrite (from scratch, web interface, multiple indicators at once, ...). But this version should still work in the meanwhile obviously.

Have you correctly entered you're API keys? In order for me to replicate this, could you provide me with a copy of your configuration file with API keys blanked out?

**Comment by uwefassnacht** [comment]
Hi @5an1ty,

thanks for the quick come back. Config file is below. The API keys work fine, I can access kraken via my local REST client (postman).

```
var config = {};

//------------------------------UserParams

//------------------------------EnableRealTrading
config.tradingEnabled = false;
// If false trading is simulated, candles are still aggregated
config.tradeAtStart = false;
// If true a trade is made immediately if the advice is either buy or sell
//------------------------------EnableRealTrading

//------------------------------exchangeSettings
config.exchangeSettings = {
  exchange: 'kraken',
  // Options: (bitstamp, kraken, btce)
  currencyPair: {pair: 'ETHXBT', asset: 'ETH', currency: 'XBT'},
  // For Bitstamp just use {pair: 'XBTUSD', asset: 'XBT', currency: 'USD'}
  // For Kraken look up the currency pairs in their API: https://api.kraken.com/0/public/AssetPairs
  // Kraken Example: {pair: 'XXBTZEUR', asset: 'XXBT', currency: 'ZEUR'}
  // For BTC-E look up the currency pairs in their API: https://btc-e.com/api/3/info
  // BTC-E Example: {pair: 'BTC_USD', asset: 'BTC', currency: 'USD'}
  tradingReserveAsset: 0,
  // Enter an amount of "asset" you would like to freeze (not trade).
  tradingReserveCurrency: 0,
  // Enter an amount of "currency" you would like to freeze (not trade).
  slippagePercentage: 0.1
  // Percentage to sell below and buy above the market.
};
//------------------------------exchangeSettings

//------------------------------APISettings
config.apiSettings = {
  bitstamp: {clientId: 0, apiKey: '', secret: ''},
  kraken: {
    apiKey: 'myAPIkey',
    secret: 'myAPIsecret'
  },
  btce: {apiKey: '', secret: ''}
};
//------------------------------APISettings

//------------------------------dbSettings
config.mongoConnectionString = 'myID:myPASSWORD@ds055885.mongolab.com:55885/bitbotdatabase';
//config.mongoConnectionString = 'localhost/bitbot';
// The connection string for your MongoDB Installation.
// Example: config.mongoConnectionString = 'username:password@example.com/mydb';
//------------------------------dbSettings

//------------------------------downloaderSettings
config.downloaderRefreshSeconds = 10;
// Best to keep this default setting unless you know what you are doing.
//------------------------------downloaderSettings

//------------------------------IndicatorSettings
config.indicatorSettings = {
  indicator: 'MACD',
  // Choices: Any indicator from the indicators folder.
  options: {neededPeriods: 26, shortPeriods: 12, longPeriods: 26, emaPeriods: 9, buyThreshold: 0, sellThreshold: 0},
  // Options needed for your indicator (Look them up in the indicator's file).
  candleStickSizeMinutes: 5
};
//------------------------------IndicatorSettings

//------------------------------orderSettings
config.orderKeepAliveMinutes = config.indicatorSettings.candleStickSizeMinutes / 10;
//------------------------------orderSettings

//------------------------------PushOver
config.pushOver = {
  enabled: false,
  pushUserId: '',
  pushAppToken: ''
};
// Push notifications via pushover (https://pushover.net/).
//------------------------------PushOver

//------------------------------BackTesting
config.backTesterSettings = {
  initialAssetBalance: 0,
  initialCurrencyBalance: 10000
};
//------------------------------BackTesting

//------------------------------Debug
config.debug = true;
//------------------------------Debug

//------------------------------UserParams

module.exports = config;
```

**Comment by 5an1ty** [comment]
@uwefassnacht One thing that might be wrong is your currency-pair:

    {pair: 'ETHXBT', asset: 'ETH', currency: 'XBT'}
should probably be:

    {pair: 'XETHXXBT', asset: 'XETH', currency: 'XXBT'}

The error you get isn't great, I should be throwing something if the currencyPair isn't found. I guess something else on the todo-list for V2.

You can find supported pairs here:
https://api.kraken.com/0/public/AssetPairs

If this doesn't help, I'll try out locally later today.

**Comment by uwefassnacht** [comment]
Works! Thanks @5an1ty !

**Comment by 5an1ty** [comment]
Great! Be sure to follow my progress here, I can't wait to push all the new things I worked on, but that's still some time in the future as web interfaces are a real struggle.
