### ISSUE TITLE
Add historic data to DB

### ISSUE THREAD

**Issue by nicoschtein** [5an1ty/BitBot#16]
It would be a good feature to be able to add historic candles to the DB to get better advice and the ability to backtest data older than the first candle generated on with the app.

**Comment by 5an1ty** [comment]
BitBot actually stores previous candles in the DB and uses them for backtesting. You need to keep the bot running to fetch more data over time. Unfortunately there's no way to retrieve detailed (tick lvl) historical data. I have been running the bot for almost two years and therefor can backtest on an extended period.

**Comment by tabenius** [comment]
Could you please provide us with your data? Otherwise me and other mortals have to wait many months for backtests to be of any use.

**Comment by tabenius** [comment]
Is it necessary to have tick level data for the indicators to work? Is it possible to make it work on e.g. 5min candlesticks?

**Comment by 5an1ty** [comment]
I don't think I can do that in a reliable way @tabenius. And I'm not sure it's actually allowed to distribute tick data of an exchange.

In principle it should also work on higher level candles as long as you don't want to go below 5 minutes.

It would go far beyond scope to download and provide historical data for every currencypair on every exchange. Especially when they throttle their API...

For now I think it's everyone's responsibility to gather data for themselves, before actually trading with the bot.

**Comment by tabenius** [comment]
I agree. Although, it would be very helpful for users that don't know kraken-api, mongodb, inner workings of BitBot to have some code snippets to guide them.

**Comment by 5an1ty** [comment]
@tabenius That's also in scope for the new version of BitBot. I want to allow users to easily subscribe to events on the bot and write their own indicators (Ticks as soon as they come in, New candles of a specific size...).
