### ISSUE TITLE
ERROR: Error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by leonardofaria** [5an1ty/BitBot#4]
Hello 

I just tried 

    npm config set strict-ssl false

...but I don't know if this problem if node or npm. Any help?

**Comment by AritzaSm** [comment]
Got that error too, 
I Fixed upgrading node, and restarting Linux Box. 

sudo apt-get update 
sudo apt-get upgrade

**Comment by 5an1ty** [comment]
Great, glad you figured it out!
