### ISSUE TITLE
Bitstamp place order error: Ensure that there are no more than 2 decimal places

### ISSUE THREAD

**Issue by MarcDiethelm** [5an1ty/BitBot#7]
Bitstamp's servers complain about the price formatting when placing an order.

`{"error":{"price":["Ensure that there are no more than 7 digits in total."]}}`
And once this is fixed
`{"error":{"price":["Ensure that there are no more than 2 decimal places."]}}`

I'll submit a PR here and in [bitstamp-api](https://github.com/5an1ty/bitstamp-api).

**Comment by 5an1ty** [comment]
Thanks, I'll have a look at the PR. Apologies for the lack of updates on BitBot by the way. I'm working on a complete rewrite that's taking quite of lot of work (web interface, trade multiple exchanges at once, talib, ...). I'm learning front end development while working on this rewrite so progress is slow, but it will get there eventually...

**Comment by MarcDiethelm** [comment]
That's good to know. I was thinking about building a simple web frontend for BitBot.

**Comment by MarcDiethelm** [comment]
I discovered another issue with Bitstamp.
`{"error":{"__all__":["Minimum order size is $5"]}}`
I added a fix to the PR.
